version: "3.9"

services:
  app:
    container_name: cc4e
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_NAME: cc4e-app
      APP_EXEC: 1
    volumes:
      - .:/app
    working_dir: /app
