version: "3.9"

services:
  app:
    build: .
      context: .
      dockerfile: Dockerfile
    environment:
      APP_NAME: cc4e-app
      APP_EXEC: 1
    volumes:
      - ./include:/app/include
      - ./src:/app/src
    working_dir: /app
